version: '3'

services:
  encoder:
    build: ./docker/encoder
    ports:
      - "1935:1935"
      - "8888:80"
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      - ./certs:/opt/certs
#
#    logging:
#      driver: splunk
#      options:
#        splunk-url: "${splunk_url_TS}"
#        splunk-token: "${splunk_token_TS}"
#        splunk-insecureskipverify: 'true'
#        splunk-format: "json"
#        splunk-verify-connection: "true"
  #transcoder_hls:
  #  build: ./docker/transcoders/hls/
  #  ports:
  #    - 1936:1935
  #    - 8081:80
  #  environment:
  #    - HTTP_PORT=80
  #    - RTMP_PORT=1935
  #  volumes:
  #    - ./certs:/opt/certs
  #  logging:
  #    driver: splunk
  #    options:
  #      splunk-url: "${splunk_url_TS}"
  #      splunk-token: "${splunk_token_TS}"
  #      splunk-insecureskipverify: 'true'
  #      splunk-format: "json"
  #      splunk-verify-connection: "true"
  #transcoder_dash:
  #  build: ./docker/transcoders/dash/
  #  ports:
  #    - 1937:1935
  #    - 8082:80
  #  environment:
  #    - HTTP_PORT=80
  #    - RTMP_PORT=1935
  #  volumes:
  #    - ./certs:/opt/certs
  #  logging:
  #    driver: splunk
  #    options:
  #      splunk-url: "${splunk_url_TS}"
  #      splunk-token: "${splunk_token_TS}"
  #      splunk-insecureskipverify: 'true'
  #      splunk-format: "json"
  #      splunk-verify-connection: "true"
  #origin:
  #  image: nginx:latest
  #  ports:
  #    - 1938:1935
  #    - 8083:80
  #    - 8443:443
  #  environment:
  #    - HTTP_PORT=80
  #    - RTMP_PORT=1935
  #  volumes:
  #    - ./certs:/opt/certs
  #  logging:
  #    driver: splunk
  #    options:
  #      splunk-url: "${splunk_url_TS}"
  #      splunk-token: "${splunk_token_TS}"
  #      splunk-insecureskipverify: 'true'
  #      splunk-format: "json"
  #      splunk-verify-connection: "true"
  web:
    build: ./docker/web
    ports:
      - "8080:80"
      - "8445:443"
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      - ./certs:/opt/certs

# NTP : https://github.com/cturra/docker-ntp